{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "all-tickers.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all-tickers.labels" . | nindent 4 }}
    cattle.io/creator: norman
  annotations:
    {{- if .Values.rancher.project }}
    field.cattle.io/projectId: {{ .Values.rancher.project }}
    {{- end }}
data:
  pipeline-enabled: {{ .Values.configMap.data."pipeline.enabled" | quote }}
  generate-enabled: {{ .Values.configMap.data."generate.enabled" | quote }}
  validate-enabled: {{ .Values.configMap.data."validate.enabled" | quote }}
  export-format: {{ .Values.configMap.data."export.format" | quote }}
{{- end }}