{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "all-tickers.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all-tickers.labels" . | nindent 4 }}
    cattle.io/creator: norman
  annotations:
    {{- if .Values.rancher.project }}
    field.cattle.io/projectId: {{ .Values.rancher.project }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}