apiVersion: v1
kind: Service
metadata:
  name: {{ include "all-tickers.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "all-tickers.labels" . | nindent 4 }}
    cattle.io/creator: norman
  annotations:
    {{- if .Values.rancher.project }}
    field.cattle.io/projectId: {{ .Values.rancher.project }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "all-tickers.selectorLabels" . | nindent 4 }}