#!/bin/bash

# All-Tickers SQLite Database Setup Script
# This script sets up SQLite database for the All-Tickers project

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Project root directory
PROJECT_ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$PROJECT_ROOT"

print_status "🚀 Setting up SQLite database for All-Tickers..."
print_status "📁 Project root: $PROJECT_ROOT"

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    print_error "Node.js is not installed. Please install Node.js first."
    exit 1
fi

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    print_error "npm is not installed. Please install npm first."
    exit 1
fi

print_success "✅ Node.js and npm are available"

# Install SQLite3 dependency if not already installed
print_status "📦 Checking SQLite3 dependency..."
if ! node -e "require('sqlite3')" 2>/dev/null; then
    print_status "Installing sqlite3 package..."
    npm install sqlite3
fi
print_success "✅ SQLite3 dependency is available"

# Check if schema file exists
SCHEMA_FILE="$PROJECT_ROOT/sqlite-schema.sql"
if [ ! -f "$SCHEMA_FILE" ]; then
    print_error "Schema file not found: $SCHEMA_FILE"
    print_error "Please ensure sqlite-schema.sql exists in the project root."
    exit 1
fi

print_success "✅ Schema file found: $SCHEMA_FILE"

# Create database and initialize schema
DATABASE_PATH="$PROJECT_ROOT/ticker_data.db"

print_status "🗄️  Initializing SQLite database..."
print_status "📍 Database location: $DATABASE_PATH"

# Remove existing database if it exists (for clean setup)
if [ -f "$DATABASE_PATH" ]; then
    print_warning "Existing database found. Creating backup..."
    cp "$DATABASE_PATH" "$DATABASE_PATH.backup.$(date +%Y%m%d_%H%M%S)"
    rm "$DATABASE_PATH"
fi

# Create database and run schema
sqlite3 "$DATABASE_PATH" < "$SCHEMA_FILE"

if [ $? -eq 0 ]; then
    print_success "✅ Database schema initialized successfully"
else
    print_error "Failed to initialize database schema"
    exit 1
fi

# Create .env file for SQLite configuration
ENV_FILE="$PROJECT_ROOT/.env"
print_status "📝 Creating environment configuration..."

# Backup existing .env if it exists
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.backup.$(date +%Y%m%d_%H%M%S)"
    print_warning "Backed up existing .env file"
fi

# Create new .env for SQLite
cat > "$ENV_FILE" << EOF
# All-Tickers SQLite Configuration
# Generated by setup-sqlite.sh on $(date)

# Database Configuration
DB_TYPE=sqlite
SQLITE_DATABASE=$DATABASE_PATH

# Server Configuration
PORT=3000
NODE_ENV=development

# Export Configuration
EXPORT_OUTPUT_DIR=./output
EXPORT_PROCESSING_DIR=./processing

# API Configuration
API_RATE_LIMIT=1000
API_TIMEOUT=30000

# Logging
LOG_LEVEL=info
EOF

print_success "✅ Environment configuration created: $ENV_FILE"

# Create output directories
mkdir -p "$PROJECT_ROOT/output"
mkdir -p "$PROJECT_ROOT/processing"
print_success "✅ Created export directories"

# Verify database setup
print_status "🔍 Verifying database setup..."

# Check if we can connect and query the database
VERIFICATION_RESULT=$(sqlite3 "$DATABASE_PATH" "SELECT name FROM sqlite_master WHERE type='table';" | wc -l)

if [ "$VERIFICATION_RESULT" -gt 0 ]; then
    print_success "✅ Database verification successful"
    print_status "📊 Found $VERIFICATION_RESULT tables in database"
else
    print_error "Database verification failed - no tables found"
    exit 1
fi

# Display database info
print_status "📈 Database Information:"
echo "   📍 Location: $DATABASE_PATH"
echo "   📏 Size: $(du -h "$DATABASE_PATH" | cut -f1)"
echo "   🗂️  Tables: $(sqlite3 "$DATABASE_PATH" "SELECT COUNT(*) FROM sqlite_master WHERE type='table';")"
echo "   🔗 Indexes: $(sqlite3 "$DATABASE_PATH" "SELECT COUNT(*) FROM sqlite_master WHERE type='index';")"

print_success "🎉 SQLite setup completed successfully!"
echo ""
print_status "📋 Next Steps:"
echo "   1. Start the application: npm start"
echo "   2. Open your browser: http://localhost:3000"
echo "   3. Click 'Generate Tickers' to populate the database"
echo ""
print_status "💡 Useful Commands:"
echo "   • View database: sqlite3 $DATABASE_PATH"
echo "   • Check tables: sqlite3 $DATABASE_PATH '.tables'"
echo "   • Database size: du -h $DATABASE_PATH"
echo ""
print_warning "📝 Note: The database is initially empty. Use the 'Generate Tickers' button in the web interface to populate it with data."